Server side file upload
alexander-e-andrews/CSSeniorDisplayProject pull request #35
Opened 2019-03-21 05:23 UTC by mirjanneza

Completed the server side file upload. Currently does not make any changes to the database (need to talk to Alex about this) and does not restrict file type as there seems to be a check already in the system. Also about those unit tests...........

2019-03-21 13:00 UTC, wassgha requested changes
LGTM in general, just a few comments and also remove that binary file (image) and add `./uploads` to `.gitignore` so that we don't accidentally put test images on the git

2019-03-21 13:00 UTC, wassgha commented on server.js
> +        pathForUploadedFiles.push(filePath)
I don't think we need the `pathForUploadedFiles` variable since we're gonna use the path immediately then store it so we don't need to keep track of all uploaded files.

2019-03-21 13:00 UTC, wassgha commented on server.js
> +var pathForUploadedFiles = []
I don't think we need the `pathForUploadedFiles` variable since we're gonna use the path immediately then store it so we don't need to keep track of all uploaded files.

2019-03-21 13:00 UTC, wassgha commented on server.js
> +      form.uploadDir = "./Uploaded_Slides"
Change to `"./uploads"`

2019-03-21 13:00 UTC, wassgha commented on server.js
> +            result: "Failed!",
Make this `result: "error"` instead so that we keep the same format across all methods

2019-03-21 13:00 UTC, wassgha commented on server.js
> +      const formidable = require("formidable")
Move to the top of the file near the other `require`s

2019-03-21 20:13 UTC, mirjanneza commented
Thanks for the feedback Wassim, one question though, when there isn't an "uploads" directory in somebody's project nothing actually saves and an error occurs, is there any way to safeguard against this without tracking the folder in git?

2019-03-21 21:53 UTC, wassgha requested changes
The changes look good! For the uploads folder, you can change the `.gitignore` line to `uploads/*`, that way it keeps the folder but not the files inside of it. Also, Travis is failing because of some styling problems, could you fix those and then we can merge!

2019-03-22 05:29 UTC, mirjanneza commented
Just fixed the styling issue as well as changed the gitignore.

P.S. I also added a hidden placeholder file to the uploads folder(since git doesn't track empty folders)

2019-03-22 09:06 UTC, wassgha approved these changes

2019-03-22 09:07 UTC, merged